// AUTO-GENERATED prototype catalog. Do not edit by hand.
// Placeholder data + media for the prototype only — replace with the
// brand's own product names, photos, and details before launch.
// Product IDs, names, and filenames are original to Taygerian.
import type { Product } from "./products";

export const products: Product[] = [
  {
    "id": "TAY-RNG-001",
    "handle": "rings-001",
    "title": "Aurelia Ring",
    "sku": "TAY-RNG-001",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "White Sapphire, round cut",
    "price": 3450,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A round white sapphire set in 18k Gold, from the Aurelia line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/rings/rings-001-1.avif",
    "images": [
      "/images/products/rings/rings-001-1.avif",
      "/images/products/rings/rings-001-2.avif",
      "/images/products/rings/rings-001-3.avif",
      "/images/products/rings/rings-001-4.avif",
      "/images/products/rings/rings-001-5.avif"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-002",
    "handle": "rings-002",
    "title": "Celestine Ring",
    "sku": "TAY-RNG-002",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "Emerald, octagon cut",
    "price": 3300,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A octagon emerald set in 18k Gold, from the Celestine line — hand-finished in our Colombo atelier.",
    "swatch": "#2f6b4c",
    "image": "/images/products/rings/rings-002-1.avif",
    "images": [
      "/images/products/rings/rings-002-1.avif",
      "/images/products/rings/rings-002-2.avif",
      "/images/products/rings/rings-002-3.avif",
      "/images/products/rings/rings-002-4.avif",
      "/images/products/rings/rings-002-5.avif",
      "/images/products/rings/rings-002-6.webm"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-003",
    "handle": "rings-003",
    "title": "Vespera Ring",
    "sku": "TAY-RNG-003",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "Yellow Sapphire",
    "price": 3150,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A yellow sapphire set in 18k Gold, from the Vespera line — hand-finished in our Colombo atelier.",
    "swatch": "#c6a54d",
    "image": "/images/products/rings/rings-003-1.avif",
    "images": [
      "/images/products/rings/rings-003-1.avif",
      "/images/products/rings/rings-003-2.avif",
      "/images/products/rings/rings-003-3.avif",
      "/images/products/rings/rings-003-4.avif"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-004",
    "handle": "rings-004",
    "title": "Seraphine Ring",
    "sku": "TAY-RNG-004",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "Mixed Gemstones",
    "price": 3000,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A round mixed gemstones set in 18k Gold, from the Seraphine line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/rings/rings-004-1.avif",
    "images": [
      "/images/products/rings/rings-004-1.avif",
      "/images/products/rings/rings-004-2.avif",
      "/images/products/rings/rings-004-3.avif",
      "/images/products/rings/rings-004-4.avif",
      "/images/products/rings/rings-004-5.avif"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-005",
    "handle": "rings-005",
    "title": "Ondine Ring",
    "sku": "TAY-RNG-005",
    "collectionHandle": "rings",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 2850,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire set in White Gold, from the Ondine line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/rings/rings-005-1.avif",
    "images": [
      "/images/products/rings/rings-005-1.avif",
      "/images/products/rings/rings-005-2.avif",
      "/images/products/rings/rings-005-3.avif",
      "/images/products/rings/rings-005-4.avif",
      "/images/products/rings/rings-005-5.avif"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-006",
    "handle": "rings-006",
    "title": "Calliope Ring",
    "sku": "TAY-RNG-006",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "Mixed Gemstones",
    "price": 2700,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones set in 18k Gold, from the Calliope line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/rings/rings-006-1.avif",
    "images": [
      "/images/products/rings/rings-006-1.avif",
      "/images/products/rings/rings-006-2.avif",
      "/images/products/rings/rings-006-3.avif",
      "/images/products/rings/rings-006-4.avif",
      "/images/products/rings/rings-006-5.avif",
      "/images/products/rings/rings-006-6.avif",
      "/images/products/rings/rings-006-7.avif"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-007",
    "handle": "rings-007",
    "title": "Isolde Ring",
    "sku": "TAY-RNG-007",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "White Sapphire, cushion cut",
    "price": 2550,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A cushion white sapphire set in 18k Gold, from the Isolde line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/rings/rings-007-1.avif",
    "images": [
      "/images/products/rings/rings-007-1.avif",
      "/images/products/rings/rings-007-2.avif",
      "/images/products/rings/rings-007-3.avif",
      "/images/products/rings/rings-007-4.avif"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-008",
    "handle": "rings-008",
    "title": "Marguerite Ring",
    "sku": "TAY-RNG-008",
    "collectionHandle": "rings",
    "metal": "White Gold",
    "stone": "Mixed Gemstones",
    "price": 2400,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones set in White Gold, from the Marguerite line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/rings/rings-008-1.avif",
    "images": [
      "/images/products/rings/rings-008-1.avif",
      "/images/products/rings/rings-008-2.avif",
      "/images/products/rings/rings-008-3.avif",
      "/images/products/rings/rings-008-4.avif",
      "/images/products/rings/rings-008-5.avif"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-009",
    "handle": "rings-009",
    "title": "Colette Ring",
    "sku": "TAY-RNG-009",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "Mixed Gemstones",
    "price": 2250,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones set in 18k Gold, from the Colette line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/rings/rings-009-1.avif",
    "images": [
      "/images/products/rings/rings-009-1.avif",
      "/images/products/rings/rings-009-2.avif",
      "/images/products/rings/rings-009-3.avif",
      "/images/products/rings/rings-009-4.avif",
      "/images/products/rings/rings-009-5.avif",
      "/images/products/rings/rings-009-6.webm"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-010",
    "handle": "rings-010",
    "title": "Genevieve Ring",
    "sku": "TAY-RNG-010",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "Mixed Gemstones",
    "price": 2100,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A cushion mixed gemstones set in 18k Gold, from the Genevieve line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/rings/rings-010-1.avif",
    "images": [
      "/images/products/rings/rings-010-1.avif",
      "/images/products/rings/rings-010-2.avif",
      "/images/products/rings/rings-010-3.avif",
      "/images/products/rings/rings-010-4.avif",
      "/images/products/rings/rings-010-5.avif",
      "/images/products/rings/rings-010-6.webm"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-011",
    "handle": "rings-011",
    "title": "Amandine Ring",
    "sku": "TAY-RNG-011",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "White Sapphire",
    "price": 1950,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire set in 18k Gold, from the Amandine line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/rings/rings-011-1.webp",
    "images": [
      "/images/products/rings/rings-011-1.webp",
      "/images/products/rings/rings-011-2.webp",
      "/images/products/rings/rings-011-3.webp",
      "/images/products/rings/rings-011-4.webm"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-012",
    "handle": "rings-012",
    "title": "Delphine Ring",
    "sku": "TAY-RNG-012",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "White Sapphire",
    "price": 1800,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire set in 18k Gold, from the Delphine line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/rings/rings-012-1.webp",
    "images": [
      "/images/products/rings/rings-012-1.webp",
      "/images/products/rings/rings-012-2.webp",
      "/images/products/rings/rings-012-3.webp",
      "/images/products/rings/rings-012-4.webm"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-013",
    "handle": "rings-013",
    "title": "Oceane Ring",
    "sku": "TAY-RNG-013",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "White Sapphire",
    "price": 1650,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire set in 18k Gold, from the Oceane line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/rings/rings-013-1.webp",
    "images": [
      "/images/products/rings/rings-013-1.webp",
      "/images/products/rings/rings-013-2.webp",
      "/images/products/rings/rings-013-3.webp",
      "/images/products/rings/rings-013-4.webp",
      "/images/products/rings/rings-013-5.webm"
    ],
    "isRing": true
  },
  {
    "id": "TAY-RNG-014",
    "handle": "rings-014",
    "title": "Sylvie Ring",
    "sku": "TAY-RNG-014",
    "collectionHandle": "rings",
    "metal": "18k Gold",
    "stone": "White Sapphire",
    "price": 1500,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire set in 18k Gold, from the Sylvie line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/rings/rings-014-1.webp",
    "images": [
      "/images/products/rings/rings-014-1.webp",
      "/images/products/rings/rings-014-2.webp",
      "/images/products/rings/rings-014-3.webp",
      "/images/products/rings/rings-014-4.webm"
    ],
    "isRing": true
  },
  {
    "id": "TAY-NCK-001",
    "handle": "necklaces-001",
    "title": "Fleur Necklace",
    "sku": "TAY-NCK-001",
    "collectionHandle": "necklaces",
    "metal": "Mixed Metals",
    "stone": "White Sapphire",
    "price": 5000,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in Mixed Metals, from the Fleur line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/necklaces/necklaces-001-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-001-1.avif",
      "/images/products/necklaces/necklaces-001-2.avif",
      "/images/products/necklaces/necklaces-001-3.avif",
      "/images/products/necklaces/necklaces-001-4.avif",
      "/images/products/necklaces/necklaces-001-5.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-002",
    "handle": "necklaces-002",
    "title": "Margaux Necklace",
    "sku": "TAY-NCK-002",
    "collectionHandle": "necklaces",
    "metal": "White Gold",
    "stone": "Emerald",
    "price": 4750,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A emerald suspended in White Gold, from the Margaux line — hand-finished in our Colombo atelier.",
    "swatch": "#2f6b4c",
    "image": "/images/products/necklaces/necklaces-002-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-002-1.avif",
      "/images/products/necklaces/necklaces-002-2.avif",
      "/images/products/necklaces/necklaces-002-3.avif",
      "/images/products/necklaces/necklaces-002-4.avif",
      "/images/products/necklaces/necklaces-002-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-003",
    "handle": "necklaces-003",
    "title": "Noemie Necklace",
    "sku": "TAY-NCK-003",
    "collectionHandle": "necklaces",
    "metal": "18k Rose Gold",
    "stone": "Pink Sapphire",
    "price": 4550,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A pink sapphire suspended in 18k Rose Gold, from the Noemie line — hand-finished in our Colombo atelier.",
    "swatch": "#b76e79",
    "image": "/images/products/necklaces/necklaces-003-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-003-1.avif",
      "/images/products/necklaces/necklaces-003-2.avif",
      "/images/products/necklaces/necklaces-003-3.avif",
      "/images/products/necklaces/necklaces-003-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-004",
    "handle": "necklaces-004",
    "title": "Clemence Necklace",
    "sku": "TAY-NCK-004",
    "collectionHandle": "necklaces",
    "metal": "18k Rose Gold",
    "stone": "White Sapphire",
    "price": 4350,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in 18k Rose Gold, from the Clemence line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/necklaces/necklaces-004-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-004-1.avif",
      "/images/products/necklaces/necklaces-004-2.avif",
      "/images/products/necklaces/necklaces-004-3.avif",
      "/images/products/necklaces/necklaces-004-4.avif",
      "/images/products/necklaces/necklaces-004-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-005",
    "handle": "necklaces-005",
    "title": "Lucienne Necklace",
    "sku": "TAY-NCK-005",
    "collectionHandle": "necklaces",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 4100,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in White Gold, from the Lucienne line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/necklaces/necklaces-005-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-005-1.avif",
      "/images/products/necklaces/necklaces-005-2.avif",
      "/images/products/necklaces/necklaces-005-3.avif",
      "/images/products/necklaces/necklaces-005-4.avif",
      "/images/products/necklaces/necklaces-005-5.avif",
      "/images/products/necklaces/necklaces-005-6.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-006",
    "handle": "necklaces-006",
    "title": "Adele Necklace",
    "sku": "TAY-NCK-006",
    "collectionHandle": "necklaces",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 3900,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in White Gold, from the Adele line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/necklaces/necklaces-006-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-006-1.avif",
      "/images/products/necklaces/necklaces-006-2.avif",
      "/images/products/necklaces/necklaces-006-3.avif",
      "/images/products/necklaces/necklaces-006-4.avif",
      "/images/products/necklaces/necklaces-006-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-007",
    "handle": "necklaces-007",
    "title": "Elodie Necklace",
    "sku": "TAY-NCK-007",
    "collectionHandle": "necklaces",
    "metal": "18k Gold",
    "stone": "Mixed Gemstones",
    "price": 3700,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones suspended in 18k Gold, from the Elodie line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/necklaces/necklaces-007-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-007-1.avif",
      "/images/products/necklaces/necklaces-007-2.avif",
      "/images/products/necklaces/necklaces-007-3.avif",
      "/images/products/necklaces/necklaces-007-4.avif",
      "/images/products/necklaces/necklaces-007-5.avif",
      "/images/products/necklaces/necklaces-007-6.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-008",
    "handle": "necklaces-008",
    "title": "Rosalind Necklace",
    "sku": "TAY-NCK-008",
    "collectionHandle": "necklaces",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 3450,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in White Gold, from the Rosalind line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/necklaces/necklaces-008-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-008-1.avif",
      "/images/products/necklaces/necklaces-008-2.avif",
      "/images/products/necklaces/necklaces-008-3.avif",
      "/images/products/necklaces/necklaces-008-4.avif",
      "/images/products/necklaces/necklaces-008-5.avif",
      "/images/products/necklaces/necklaces-008-6.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-009",
    "handle": "necklaces-009",
    "title": "Vivienne Necklace",
    "sku": "TAY-NCK-009",
    "collectionHandle": "necklaces",
    "metal": "White Gold",
    "stone": "Mixed Gemstones",
    "price": 3250,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones suspended in White Gold, from the Vivienne line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/necklaces/necklaces-009-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-009-1.avif",
      "/images/products/necklaces/necklaces-009-2.avif",
      "/images/products/necklaces/necklaces-009-3.avif",
      "/images/products/necklaces/necklaces-009-4.avif",
      "/images/products/necklaces/necklaces-009-5.avif",
      "/images/products/necklaces/necklaces-009-6.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-010",
    "handle": "necklaces-010",
    "title": "Camille Necklace",
    "sku": "TAY-NCK-010",
    "collectionHandle": "necklaces",
    "metal": "White Gold",
    "stone": "Blue Sapphire",
    "price": 3050,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": {
      "lab": "GIA",
      "reportNumber": "GIA-NCK1000370",
      "origin": "Ceylon (Sri Lanka)"
    },
    "description": "A blue sapphire suspended in White Gold, from the Camille line — hand-finished in our Colombo atelier.",
    "swatch": "#2f4c82",
    "image": "/images/products/necklaces/necklaces-010-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-010-1.avif",
      "/images/products/necklaces/necklaces-010-2.avif",
      "/images/products/necklaces/necklaces-010-3.avif",
      "/images/products/necklaces/necklaces-010-4.avif",
      "/images/products/necklaces/necklaces-010-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-011",
    "handle": "necklaces-011",
    "title": "Beatrix Necklace",
    "sku": "TAY-NCK-011",
    "collectionHandle": "necklaces",
    "metal": "White Gold",
    "stone": "Mixed Gemstones",
    "price": 2800,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones suspended in White Gold, from the Beatrix line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/necklaces/necklaces-011-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-011-1.avif",
      "/images/products/necklaces/necklaces-011-2.avif",
      "/images/products/necklaces/necklaces-011-3.avif",
      "/images/products/necklaces/necklaces-011-4.avif",
      "/images/products/necklaces/necklaces-011-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-012",
    "handle": "necklaces-012",
    "title": "Ophelie Necklace",
    "sku": "TAY-NCK-012",
    "collectionHandle": "necklaces",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 2600,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in White Gold, from the Ophelie line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/necklaces/necklaces-012-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-012-1.avif",
      "/images/products/necklaces/necklaces-012-2.avif",
      "/images/products/necklaces/necklaces-012-3.avif",
      "/images/products/necklaces/necklaces-012-4.avif",
      "/images/products/necklaces/necklaces-012-5.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-NCK-013",
    "handle": "necklaces-013",
    "title": "Anouk Necklace",
    "sku": "TAY-NCK-013",
    "collectionHandle": "necklaces",
    "metal": "18k Gold",
    "stone": "Mixed Gemstones",
    "price": 2400,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones suspended in 18k Gold, from the Anouk line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/necklaces/necklaces-013-1.avif",
    "images": [
      "/images/products/necklaces/necklaces-013-1.avif",
      "/images/products/necklaces/necklaces-013-2.avif",
      "/images/products/necklaces/necklaces-013-3.avif",
      "/images/products/necklaces/necklaces-013-4.avif",
      "/images/products/necklaces/necklaces-013-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-001",
    "handle": "pendants-001",
    "title": "Mirabelle Pendant",
    "sku": "TAY-PND-001",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 2300,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in White Gold, from the Mirabelle line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-001-1.avif",
    "images": [
      "/images/products/pendants/pendants-001-1.avif",
      "/images/products/pendants/pendants-001-2.avif",
      "/images/products/pendants/pendants-001-3.avif",
      "/images/products/pendants/pendants-001-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-002",
    "handle": "pendants-002",
    "title": "Cosima Pendant",
    "sku": "TAY-PND-002",
    "collectionHandle": "pendants",
    "metal": "18k Gold",
    "stone": "White Sapphire",
    "price": 2200,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in 18k Gold, from the Cosima line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-002-1.avif",
    "images": [
      "/images/products/pendants/pendants-002-1.avif",
      "/images/products/pendants/pendants-002-2.avif",
      "/images/products/pendants/pendants-002-3.avif",
      "/images/products/pendants/pendants-002-4.avif",
      "/images/products/pendants/pendants-002-5.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-003",
    "handle": "pendants-003",
    "title": "Leontine Pendant",
    "sku": "TAY-PND-003",
    "collectionHandle": "pendants",
    "metal": "18k Gold",
    "stone": "White Sapphire, round cut",
    "price": 2100,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A round white sapphire suspended in 18k Gold, from the Leontine line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-003-1.avif",
    "images": [
      "/images/products/pendants/pendants-003-1.avif",
      "/images/products/pendants/pendants-003-2.avif",
      "/images/products/pendants/pendants-003-3.avif",
      "/images/products/pendants/pendants-003-4.avif",
      "/images/products/pendants/pendants-003-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-004",
    "handle": "pendants-004",
    "title": "Perrine Pendant",
    "sku": "TAY-PND-004",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "Blue Sapphire, octagon cut",
    "price": 2000,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": {
      "lab": "GRS",
      "reportNumber": "GRS-PND1000148",
      "origin": "Ceylon (Sri Lanka)"
    },
    "description": "A octagon blue sapphire suspended in White Gold, from the Perrine line — hand-finished in our Colombo atelier.",
    "swatch": "#2f4c82",
    "image": "/images/products/pendants/pendants-004-1.avif",
    "images": [
      "/images/products/pendants/pendants-004-1.avif",
      "/images/products/pendants/pendants-004-2.avif",
      "/images/products/pendants/pendants-004-3.avif",
      "/images/products/pendants/pendants-004-4.avif",
      "/images/products/pendants/pendants-004-5.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-005",
    "handle": "pendants-005",
    "title": "Sidonie Pendant",
    "sku": "TAY-PND-005",
    "collectionHandle": "pendants",
    "metal": "18k Rose Gold",
    "stone": "Mixed Gemstones",
    "price": 1900,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones suspended in 18k Rose Gold, from the Sidonie line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/pendants/pendants-005-1.avif",
    "images": [
      "/images/products/pendants/pendants-005-1.avif",
      "/images/products/pendants/pendants-005-2.avif",
      "/images/products/pendants/pendants-005-3.avif",
      "/images/products/pendants/pendants-005-4.avif",
      "/images/products/pendants/pendants-005-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-006",
    "handle": "pendants-006",
    "title": "Albane Pendant",
    "sku": "TAY-PND-006",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 1800,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in White Gold, from the Albane line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-006-1.avif",
    "images": [
      "/images/products/pendants/pendants-006-1.avif",
      "/images/products/pendants/pendants-006-2.avif",
      "/images/products/pendants/pendants-006-3.avif",
      "/images/products/pendants/pendants-006-4.avif",
      "/images/products/pendants/pendants-006-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-007",
    "handle": "pendants-007",
    "title": "Capucine Pendant",
    "sku": "TAY-PND-007",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "Blue Sapphire",
    "price": 1700,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A blue sapphire suspended in White Gold, from the Capucine line — hand-finished in our Colombo atelier.",
    "swatch": "#2f4c82",
    "image": "/images/products/pendants/pendants-007-1.avif",
    "images": [
      "/images/products/pendants/pendants-007-1.avif",
      "/images/products/pendants/pendants-007-2.avif",
      "/images/products/pendants/pendants-007-3.avif",
      "/images/products/pendants/pendants-007-4.avif",
      "/images/products/pendants/pendants-007-5.avif",
      "/images/products/pendants/pendants-007-6.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-008",
    "handle": "pendants-008",
    "title": "Lisette Pendant",
    "sku": "TAY-PND-008",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "Pink Sapphire",
    "price": 1600,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A pink sapphire suspended in White Gold, from the Lisette line — hand-finished in our Colombo atelier.",
    "swatch": "#b76e79",
    "image": "/images/products/pendants/pendants-008-1.avif",
    "images": [
      "/images/products/pendants/pendants-008-1.avif",
      "/images/products/pendants/pendants-008-2.avif",
      "/images/products/pendants/pendants-008-3.avif",
      "/images/products/pendants/pendants-008-4.avif",
      "/images/products/pendants/pendants-008-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-009",
    "handle": "pendants-009",
    "title": "Yseult Pendant",
    "sku": "TAY-PND-009",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 1550,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in White Gold, from the Yseult line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-009-1.avif",
    "images": [
      "/images/products/pendants/pendants-009-1.avif",
      "/images/products/pendants/pendants-009-2.avif",
      "/images/products/pendants/pendants-009-3.avif",
      "/images/products/pendants/pendants-009-4.avif",
      "/images/products/pendants/pendants-009-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-010",
    "handle": "pendants-010",
    "title": "Bathilde Pendant",
    "sku": "TAY-PND-010",
    "collectionHandle": "pendants",
    "metal": "18k Rose Gold",
    "stone": "White Sapphire, marquise cut",
    "price": 1450,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A marquise white sapphire suspended in 18k Rose Gold, from the Bathilde line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-010-1.avif",
    "images": [
      "/images/products/pendants/pendants-010-1.avif",
      "/images/products/pendants/pendants-010-2.avif",
      "/images/products/pendants/pendants-010-3.avif",
      "/images/products/pendants/pendants-010-4.avif",
      "/images/products/pendants/pendants-010-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-011",
    "handle": "pendants-011",
    "title": "Sabine Pendant",
    "sku": "TAY-PND-011",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "Blue Sapphire, cushion cut",
    "price": 1350,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A cushion blue sapphire suspended in White Gold, from the Sabine line — hand-finished in our Colombo atelier.",
    "swatch": "#2f4c82",
    "image": "/images/products/pendants/pendants-011-1.avif",
    "images": [
      "/images/products/pendants/pendants-011-1.avif",
      "/images/products/pendants/pendants-011-2.avif",
      "/images/products/pendants/pendants-011-3.avif",
      "/images/products/pendants/pendants-011-4.avif",
      "/images/products/pendants/pendants-011-5.avif",
      "/images/products/pendants/pendants-011-6.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-012",
    "handle": "pendants-012",
    "title": "Honorine Pendant",
    "sku": "TAY-PND-012",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "Blue Sapphire, round cut",
    "price": 1250,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": {
      "lab": "GRS",
      "reportNumber": "GRS-PND1000444",
      "origin": "Ceylon (Sri Lanka)"
    },
    "description": "A round blue sapphire suspended in White Gold, from the Honorine line — hand-finished in our Colombo atelier.",
    "swatch": "#2f4c82",
    "image": "/images/products/pendants/pendants-012-1.avif",
    "images": [
      "/images/products/pendants/pendants-012-1.avif",
      "/images/products/pendants/pendants-012-2.avif",
      "/images/products/pendants/pendants-012-3.avif",
      "/images/products/pendants/pendants-012-4.avif",
      "/images/products/pendants/pendants-012-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-013",
    "handle": "pendants-013",
    "title": "Emmeline Pendant",
    "sku": "TAY-PND-013",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "White Sapphire, cushion cut",
    "price": 1150,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A cushion white sapphire suspended in White Gold, from the Emmeline line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-013-1.avif",
    "images": [
      "/images/products/pendants/pendants-013-1.avif",
      "/images/products/pendants/pendants-013-2.avif",
      "/images/products/pendants/pendants-013-3.avif",
      "/images/products/pendants/pendants-013-4.avif",
      "/images/products/pendants/pendants-013-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-014",
    "handle": "pendants-014",
    "title": "Aurore Pendant",
    "sku": "TAY-PND-014",
    "collectionHandle": "pendants",
    "metal": "Mixed Metals",
    "stone": "White Sapphire, round cut",
    "price": 1050,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A round white sapphire suspended in Mixed Metals, from the Aurore line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-014-1.avif",
    "images": [
      "/images/products/pendants/pendants-014-1.avif",
      "/images/products/pendants/pendants-014-2.avif",
      "/images/products/pendants/pendants-014-3.avif",
      "/images/products/pendants/pendants-014-4.avif",
      "/images/products/pendants/pendants-014-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-015",
    "handle": "pendants-015",
    "title": "Ninon Pendant",
    "sku": "TAY-PND-015",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 950,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in White Gold, from the Ninon line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-015-1.avif",
    "images": [
      "/images/products/pendants/pendants-015-1.avif",
      "/images/products/pendants/pendants-015-2.avif",
      "/images/products/pendants/pendants-015-3.avif",
      "/images/products/pendants/pendants-015-4.avif",
      "/images/products/pendants/pendants-015-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-016",
    "handle": "pendants-016",
    "title": "Aurelia Pendant",
    "sku": "TAY-PND-016",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 850,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in White Gold, from the Aurelia line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-016-1.avif",
    "images": [
      "/images/products/pendants/pendants-016-1.avif",
      "/images/products/pendants/pendants-016-2.avif",
      "/images/products/pendants/pendants-016-3.avif",
      "/images/products/pendants/pendants-016-4.avif",
      "/images/products/pendants/pendants-016-5.avif",
      "/images/products/pendants/pendants-016-6.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-017",
    "handle": "pendants-017",
    "title": "Celestine Pendant",
    "sku": "TAY-PND-017",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "Mixed Gemstones",
    "price": 750,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones suspended in White Gold, from the Celestine line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/pendants/pendants-017-1.avif",
    "images": [
      "/images/products/pendants/pendants-017-1.avif",
      "/images/products/pendants/pendants-017-2.avif",
      "/images/products/pendants/pendants-017-3.avif",
      "/images/products/pendants/pendants-017-4.avif",
      "/images/products/pendants/pendants-017-5.avif",
      "/images/products/pendants/pendants-017-6.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-018",
    "handle": "pendants-018",
    "title": "Vespera Pendant",
    "sku": "TAY-PND-018",
    "collectionHandle": "pendants",
    "metal": "18k Gold",
    "stone": "Ruby",
    "price": 2350,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A ruby suspended in 18k Gold, from the Vespera line — hand-finished in our Colombo atelier.",
    "swatch": "#7a2230",
    "image": "/images/products/pendants/pendants-018-1.avif",
    "images": [
      "/images/products/pendants/pendants-018-1.avif",
      "/images/products/pendants/pendants-018-2.avif",
      "/images/products/pendants/pendants-018-3.avif",
      "/images/products/pendants/pendants-018-4.avif",
      "/images/products/pendants/pendants-018-5.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-019",
    "handle": "pendants-019",
    "title": "Seraphine Pendant",
    "sku": "TAY-PND-019",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "White Sapphire, round cut",
    "price": 2250,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A round white sapphire suspended in White Gold, from the Seraphine line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-019-1.avif",
    "images": [
      "/images/products/pendants/pendants-019-1.avif",
      "/images/products/pendants/pendants-019-2.avif",
      "/images/products/pendants/pendants-019-3.avif",
      "/images/products/pendants/pendants-019-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-020",
    "handle": "pendants-020",
    "title": "Ondine Pendant",
    "sku": "TAY-PND-020",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 2150,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire suspended in White Gold, from the Ondine line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/pendants/pendants-020-1.avif",
    "images": [
      "/images/products/pendants/pendants-020-1.avif",
      "/images/products/pendants/pendants-020-2.avif",
      "/images/products/pendants/pendants-020-3.avif",
      "/images/products/pendants/pendants-020-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-PND-021",
    "handle": "pendants-021",
    "title": "Calliope Pendant",
    "sku": "TAY-PND-021",
    "collectionHandle": "pendants",
    "metal": "White Gold",
    "stone": "Blue Sapphire",
    "price": 2050,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A blue sapphire suspended in White Gold, from the Calliope line — hand-finished in our Colombo atelier.",
    "swatch": "#2f4c82",
    "image": "/images/products/pendants/pendants-021-1.avif",
    "images": [
      "/images/products/pendants/pendants-021-1.avif",
      "/images/products/pendants/pendants-021-2.avif",
      "/images/products/pendants/pendants-021-3.avif",
      "/images/products/pendants/pendants-021-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-EAR-001",
    "handle": "earrings-001",
    "title": "Isolde Drop Earrings",
    "sku": "TAY-EAR-001",
    "collectionHandle": "earrings",
    "metal": "White Gold",
    "stone": "White Sapphire, round cut",
    "price": 2700,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A round white sapphire suspended in White Gold, from the Isolde line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/earrings/earrings-001-1.avif",
    "images": [
      "/images/products/earrings/earrings-001-1.avif",
      "/images/products/earrings/earrings-001-2.avif",
      "/images/products/earrings/earrings-001-3.avif",
      "/images/products/earrings/earrings-001-4.avif",
      "/images/products/earrings/earrings-001-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-EAR-002",
    "handle": "earrings-002",
    "title": "Marguerite Drop Earrings",
    "sku": "TAY-EAR-002",
    "collectionHandle": "earrings",
    "metal": "White Gold",
    "stone": "Pink Sapphire",
    "price": 2550,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A pink sapphire suspended in White Gold, from the Marguerite line — hand-finished in our Colombo atelier.",
    "swatch": "#b76e79",
    "image": "/images/products/earrings/earrings-002-1.avif",
    "images": [
      "/images/products/earrings/earrings-002-1.avif",
      "/images/products/earrings/earrings-002-2.avif",
      "/images/products/earrings/earrings-002-3.avif",
      "/images/products/earrings/earrings-002-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-EAR-003",
    "handle": "earrings-003",
    "title": "Colette Drop Earrings",
    "sku": "TAY-EAR-003",
    "collectionHandle": "earrings",
    "metal": "18k Gold",
    "stone": "Mixed Gemstones",
    "price": 2450,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones suspended in 18k Gold, from the Colette line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/earrings/earrings-003-1.avif",
    "images": [
      "/images/products/earrings/earrings-003-1.avif",
      "/images/products/earrings/earrings-003-2.avif",
      "/images/products/earrings/earrings-003-3.avif",
      "/images/products/earrings/earrings-003-4.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-EAR-004",
    "handle": "earrings-004",
    "title": "Genevieve Drop Earrings",
    "sku": "TAY-EAR-004",
    "collectionHandle": "earrings",
    "metal": "18k Gold",
    "stone": "Mixed Gemstones",
    "price": 2300,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones suspended in 18k Gold, from the Genevieve line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/earrings/earrings-004-1.avif",
    "images": [
      "/images/products/earrings/earrings-004-1.avif",
      "/images/products/earrings/earrings-004-2.avif",
      "/images/products/earrings/earrings-004-3.avif",
      "/images/products/earrings/earrings-004-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-EAR-005",
    "handle": "earrings-005",
    "title": "Amandine Drop Earrings",
    "sku": "TAY-EAR-005",
    "collectionHandle": "earrings",
    "metal": "White Gold",
    "stone": "Emerald",
    "price": 2200,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A emerald suspended in White Gold, from the Amandine line — hand-finished in our Colombo atelier.",
    "swatch": "#2f6b4c",
    "image": "/images/products/earrings/earrings-005-1.avif",
    "images": [
      "/images/products/earrings/earrings-005-1.avif",
      "/images/products/earrings/earrings-005-2.avif",
      "/images/products/earrings/earrings-005-3.avif",
      "/images/products/earrings/earrings-005-4.avif",
      "/images/products/earrings/earrings-005-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-EAR-006",
    "handle": "earrings-006",
    "title": "Delphine Drop Earrings",
    "sku": "TAY-EAR-006",
    "collectionHandle": "earrings",
    "metal": "White Gold",
    "stone": "White Sapphire, round cut",
    "price": 2050,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A round white sapphire suspended in White Gold, from the Delphine line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/earrings/earrings-006-1.avif",
    "images": [
      "/images/products/earrings/earrings-006-1.avif",
      "/images/products/earrings/earrings-006-2.avif",
      "/images/products/earrings/earrings-006-3.avif",
      "/images/products/earrings/earrings-006-4.avif",
      "/images/products/earrings/earrings-006-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-EAR-007",
    "handle": "earrings-007",
    "title": "Oceane Drop Earrings",
    "sku": "TAY-EAR-007",
    "collectionHandle": "earrings",
    "metal": "18k Gold",
    "stone": "White Sapphire, round cut",
    "price": 1950,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A round white sapphire suspended in 18k Gold, from the Oceane line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/earrings/earrings-007-1.avif",
    "images": [
      "/images/products/earrings/earrings-007-1.avif",
      "/images/products/earrings/earrings-007-2.avif",
      "/images/products/earrings/earrings-007-3.avif",
      "/images/products/earrings/earrings-007-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-BRC-001",
    "handle": "bracelets-001",
    "title": "Sylvie Bracelet",
    "sku": "TAY-BRC-001",
    "collectionHandle": "bracelets",
    "metal": "18k Rose Gold",
    "stone": "White Sapphire",
    "price": 3250,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire arranged in 18k Rose Gold, from the Sylvie line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/bracelets/bracelets-001-1.avif",
    "images": [
      "/images/products/bracelets/bracelets-001-1.avif",
      "/images/products/bracelets/bracelets-001-2.avif",
      "/images/products/bracelets/bracelets-001-3.avif",
      "/images/products/bracelets/bracelets-001-4.avif",
      "/images/products/bracelets/bracelets-001-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-BRC-002",
    "handle": "bracelets-002",
    "title": "Fleur Bracelet",
    "sku": "TAY-BRC-002",
    "collectionHandle": "bracelets",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 3100,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire arranged in White Gold, from the Fleur line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/bracelets/bracelets-002-1.avif",
    "images": [
      "/images/products/bracelets/bracelets-002-1.avif",
      "/images/products/bracelets/bracelets-002-2.avif",
      "/images/products/bracelets/bracelets-002-3.avif",
      "/images/products/bracelets/bracelets-002-4.avif",
      "/images/products/bracelets/bracelets-002-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-BRC-003",
    "handle": "bracelets-003",
    "title": "Margaux Bracelet",
    "sku": "TAY-BRC-003",
    "collectionHandle": "bracelets",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 2950,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire arranged in White Gold, from the Margaux line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/bracelets/bracelets-003-1.avif",
    "images": [
      "/images/products/bracelets/bracelets-003-1.avif",
      "/images/products/bracelets/bracelets-003-2.avif",
      "/images/products/bracelets/bracelets-003-3.avif",
      "/images/products/bracelets/bracelets-003-4.avif",
      "/images/products/bracelets/bracelets-003-5.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-BRC-004",
    "handle": "bracelets-004",
    "title": "Noemie Bracelet",
    "sku": "TAY-BRC-004",
    "collectionHandle": "bracelets",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 2850,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire arranged in White Gold, from the Noemie line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/bracelets/bracelets-004-1.avif",
    "images": [
      "/images/products/bracelets/bracelets-004-1.avif",
      "/images/products/bracelets/bracelets-004-2.avif",
      "/images/products/bracelets/bracelets-004-3.avif",
      "/images/products/bracelets/bracelets-004-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-BRC-005",
    "handle": "bracelets-005",
    "title": "Clemence Bracelet",
    "sku": "TAY-BRC-005",
    "collectionHandle": "bracelets",
    "metal": "White Gold",
    "stone": "Emerald",
    "price": 2700,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A emerald arranged in White Gold, from the Clemence line — hand-finished in our Colombo atelier.",
    "swatch": "#2f6b4c",
    "image": "/images/products/bracelets/bracelets-005-1.avif",
    "images": [
      "/images/products/bracelets/bracelets-005-1.avif",
      "/images/products/bracelets/bracelets-005-2.avif",
      "/images/products/bracelets/bracelets-005-3.avif",
      "/images/products/bracelets/bracelets-005-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-BRC-006",
    "handle": "bracelets-006",
    "title": "Lucienne Bracelet",
    "sku": "TAY-BRC-006",
    "collectionHandle": "bracelets",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 2550,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire arranged in White Gold, from the Lucienne line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/bracelets/bracelets-006-1.avif",
    "images": [
      "/images/products/bracelets/bracelets-006-1.avif",
      "/images/products/bracelets/bracelets-006-2.avif",
      "/images/products/bracelets/bracelets-006-3.avif",
      "/images/products/bracelets/bracelets-006-4.avif",
      "/images/products/bracelets/bracelets-006-5.avif",
      "/images/products/bracelets/bracelets-006-6.webm",
      "/images/products/bracelets/bracelets-006-7.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-BRC-007",
    "handle": "bracelets-007",
    "title": "Adele Bracelet",
    "sku": "TAY-BRC-007",
    "collectionHandle": "bracelets",
    "metal": "18k Gold",
    "stone": "Mixed Gemstones",
    "price": 2400,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A round mixed gemstones arranged in 18k Gold, from the Adele line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/bracelets/bracelets-007-1.avif",
    "images": [
      "/images/products/bracelets/bracelets-007-1.avif",
      "/images/products/bracelets/bracelets-007-2.avif",
      "/images/products/bracelets/bracelets-007-3.avif",
      "/images/products/bracelets/bracelets-007-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-BNG-001",
    "handle": "bangles-001",
    "title": "Elodie Bangle",
    "sku": "TAY-BNG-001",
    "collectionHandle": "bangles",
    "metal": "18k Gold",
    "stone": "Mixed Gemstones",
    "price": 5350,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A mixed gemstones arranged in 18k Gold, from the Elodie line — hand-finished in our Colombo atelier.",
    "swatch": "#8a6fae",
    "image": "/images/products/bangles/bangles-001-1.avif",
    "images": [
      "/images/products/bangles/bangles-001-1.avif",
      "/images/products/bangles/bangles-001-2.avif",
      "/images/products/bangles/bangles-001-3.avif",
      "/images/products/bangles/bangles-001-4.avif"
    ],
    "isRing": false
  },
  {
    "id": "TAY-BNG-002",
    "handle": "bangles-002",
    "title": "Rosalind Bangle",
    "sku": "TAY-BNG-002",
    "collectionHandle": "bangles",
    "metal": "18k Gold",
    "stone": "Ruby, pear cut",
    "price": 5150,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A pear ruby arranged in 18k Gold, from the Rosalind line — hand-finished in our Colombo atelier.",
    "swatch": "#7a2230",
    "image": "/images/products/bangles/bangles-002-1.avif",
    "images": [
      "/images/products/bangles/bangles-002-1.avif",
      "/images/products/bangles/bangles-002-2.avif",
      "/images/products/bangles/bangles-002-3.avif",
      "/images/products/bangles/bangles-002-4.avif",
      "/images/products/bangles/bangles-002-5.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-BNG-003",
    "handle": "bangles-003",
    "title": "Vivienne Bangle",
    "sku": "TAY-BNG-003",
    "collectionHandle": "bangles",
    "metal": "White Gold",
    "stone": "White Sapphire",
    "price": 4900,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A white sapphire arranged in White Gold, from the Vivienne line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/bangles/bangles-003-1.avif",
    "images": [
      "/images/products/bangles/bangles-003-1.avif",
      "/images/products/bangles/bangles-003-2.avif",
      "/images/products/bangles/bangles-003-3.avif",
      "/images/products/bangles/bangles-003-4.avif",
      "/images/products/bangles/bangles-003-5.webm"
    ],
    "isRing": false
  },
  {
    "id": "TAY-BNG-004",
    "handle": "bangles-004",
    "title": "Camille Bangle",
    "sku": "TAY-BNG-004",
    "collectionHandle": "bangles",
    "metal": "18k Gold",
    "stone": "White Sapphire, round cut",
    "price": 4700,
    "currency": "USD",
    "oneOfAKind": false,
    "certification": null,
    "description": "A round white sapphire arranged in 18k Gold, from the Camille line — hand-finished in our Colombo atelier.",
    "swatch": "#dfdbd0",
    "image": "/images/products/bangles/bangles-004-1.avif",
    "images": [
      "/images/products/bangles/bangles-004-1.avif",
      "/images/products/bangles/bangles-004-2.avif",
      "/images/products/bangles/bangles-004-3.avif",
      "/images/products/bangles/bangles-004-4.avif"
    ],
    "isRing": false
  }
];
